const SUPABASE_URL = 'https://wabelblydkhfpvvxwrzd.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhYmVsYmx5ZGtoZnB2dnh3cnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNTY4ODYsImV4cCI6MjA3NzgzMjg4Nn0.6YrnmhAk_6ZqdKYe9h6fNCkvaHKCHBscHTMZTIzkiDU';

const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
